### ISSUE TITLE
Minimal p2p Storage Engine

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-codex#13]
# Minimal Storage Engine

## Summary

The storage engine is in charge of finding, storing and exchanging chunks in the system. The engine is agnostic to the node type and all nodes rely on it to exchange and store chunks.

### Components

Bellow is a quick outline of some major components that comprise the storage engine.

```
+---------------------------------------------------------------------+
|  Storage Engine                                                     |
|  ---------------------   -----------------------------------------  |
|  | local chunk store |   | network chunk store                   |  |
|  |                   |   -----------------------------------------  |
|  |                   |                                              |
|  |                   |   -------------------   -------------------  |
|  |                   |   | discovery (DHT) |   | chunk exchange  |  |
|  ---------------------   -------------------   -------------------  |
|                                                                     |
|  ---------------------   -----------------------------------------  |
|  | file system       |   |               libp2p                  |  |
|  ---------------------   -----------------------------------------  |
+---------------------------------------------------------------------+
```

- Local and remote chunk stores
- A discovery component
  - DHT
  - Peer Exchange (PeX)
- An exchange mechanism in charge of sending and requesting chunks - chunk exchange
- libp2p as the p2p network stack

The next section will outline how each component fits in with the rest and what functions it performs.

#### Chunk stores

The chunk stores are in charge of storing and retrieving chunks. There are two chunk stores in the dagger system:

- Local - is in charge of storing and retrieving chunks from the process local storage
- Network - is in charge of storing and retrieving chunks from the p2p network

#### Discovery

- DHT - This is a kademlia DHT used to locate peers that are __potentially__ in possesion of a chunk
  - The same mechanism is also used for arbitrary node discovery, where the DHT is queried for some random hash and the nodes found along the query path are recorded - this is known as a random walk
- PeX - This is a simple discovery mechanism and stands for "Peer eXchange". It works by exchanging lists of peers on connect and periodically, during the lifetime of the connection

#### Chunk Exchange

The chunk exchange (CE) mechanism is in charge of locating, negotiating and exchanging chunks with other peers in the Dagger network. It interacts with other subsystems such as the chunk store and discovery. Chunk requests are handled slightly differently depending if the request was issued locally or remotely.

A local request is handled by first looking for a chunk in the local chunk store and if not found issuing a request to the network/remote store.

A remote request is handled similar to a local request, by first looking in the local chunk store and if it's not found by checking if the already connected peers have the chunk. A peer might decide to engage in "opportunistic providing" which is when, peers that don't have a chunk locally but know a peer that has it, might offer to forward the chunk to the requesting peer for a premium. The requesting peer would usually not know that the chunk is being forwared.

In the case that the remote peer has exhausted it's quotas the request might not be honored and the peer might be placed in a cooldown list or kicked altogether.

#### Network stack

All network interactions are backed by libp2p which is capable of providing multitransport communication over tcp, websockets and quic; as well as channel multiplexing, encryption, connection management and several other miscellaneous functions like gossiping.

## Interactions overview

This section outlines common interactions that the storage engine should support.

### Fetching Chunks

1. Chunks requested locally have roughly the following flow
   1. A top-level chunk (a chunk that links to other chunks) or a terminal chunk  (a chunk that does not link to any other chunks) is requested
   2. The chunk is looked up in the chunk store manager
      1. If the chunk exists locally it is streamed back
      2. Otherwise, the chunk store manager requests it from the network store which in turn
         1. Checks if any of the already connected peers has the chunk and if so requests it from one or more peers
         2. Otherwise, it queries the discovery subsystem for peers that announce the chunk
         3. Once peers are discovered, the CE subsystem will attempt to fetch this chunks since they are marked as pending
      3. If no peers can be found in time the pending chunks will eventually expire and the request will fail
2. Chunks requested by remote peers are looked up in the local store and served to the remote peer if found, however, if the local peer decides to engage in "opportunistic providing", the same flow as in `1` is engaged

### Uploading Chunks

NOTE1: The flow outlined here is simplified and doesn't go into details that might be important for auditable long term storage, this will be covered in a sepparate document/issue.

NOTE2: The details of how the chunked dataset is represented and addressed are still TBD and will be covered in it's own document/issue.

To upload a file or arbitrary dataset, the data is chunked and a hash capable of addressing the entire dataset is produced. The hash is subsequently published to the DHT or distributed to connected and/or discovered peers which might request some or all the chunks from the peer.

### Discovering Peers

- Chunk based discovery over a DHT is performed when a peer is looking for other peers that announce a specific hash. Peers announce the chunks they are in possession of periodically to the DHT in order to increase their ability to be discovered. Peers might want to engage in this due to several reasons
   - to make a profit from download fees
   - for altruistic reasons to increase access to some specific piece of data
   - etc...

- A random walk is used to discover and connect to random peers when initially joining the network or when chunk based discovery failed to return enough good peers. Peers are potentially more likely to announce a chunk on connect than over the DHT.

- PeX is engaged everytime a new peer is connected and subsequently repeated over the lifetime of a connection.

## Functional Outline

The engine should implement the following functionality

- [x] #20
  - [x] This entails chunking the data and organizing it into some sort of authenticated data structure such as a merkle tree
- [x] #21
  - [x] This entails traversing an authenticated data structure and downloading the referenced nodes and leafs as they are discovered
- [x] #22
  - [x] A chunk provider will announce chunks it stores
    - [x] Over a DHT
    - [x] Through an explicit chunks list exchanged on connect and/or periodically over the lifetime of a connection
- [x] #23
  - [x] A client will be able to discover chunks
    - [x] Over a DHT
    - [x] Through an explicit chunks list exchanged on connect and/or periodically over the lifetime of a connection

## Acceptance Criteria

- [x] A node should be able to uploading and downloading chunks
- [x] A node should be able to announce chunks over a DHT and explicit chunk list exchange
- [x] A node should be able to discover  chunks over a DHT and explicit chunk list exchange
