### ISSUE TITLE
Distributed Testing High Level Requirements and Roadmap

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-codex#350]
# Distributed Testing High Level Requirements and Roadmap

## Background

As Codex approaches its MVP (Minimal Viable Product) release, stability and reliability as well as scalability and security become critical and require a more focused effort. This issue attempts to capture the requirements to get the current PoC implementation to it's desired MVP state.

## Requirements

The Codex protocol consists of several main components which needs to be tested in isolation as well as in concert. These are:

- The p2p related pieces
- The marketplace and consensus related pieces
- The remote auditing related pieces

For each of these we want:

- To test correctness, stability and scalability.
- Simulate different network and load conditions.
  - Ability to control the network topology and conditions (throttling, packet-loss, etc...)
- Collect and inspect metrics and logs in real time and post factum.
- Reproduce/rerun each specific configuration and test at will.
- Ability to run on remote elastic infrastructure (AWS, etc...) as well as locally.
  - We want to scale the number of nodes according to our needs.
  - Possibly run with and without containerization.

## Testing Approaches

There are two main testing approaches that we're pursuing:

- Blackbox (distributed) testing
  - These rely on distributed testing frameworks such as
    - [testground](https://github.com/testground/)
    - [kurtosis](https://www.kurtosis.com/)
    - [clustertest](https://github.com/guseggert/clustertest)
    - [beekeeper](https://github.com/ethersphere/beekeeper)
- Whitebox (testnets) testing
  - These relies on user testing and requires supporting infrastructure to spin up both internal and external testnets on an as needed basis

I believe that the testnet requirements are relatively simple, both in terms of infrastructure as well as setup complexity. Once there is a baseline configuration it can be reused many times, with minimal changes, accross different iterations of the testnet. In terms of infrastructure, the requirements seem relatively low - it should support a basaline number of nodes (10, 20, 30?), out of which, a few would be bootstrap nodes, with mildly higher requirements.

The distributed testing approach however is more involved and requires a lot more effort, both in the initial setup phases as well as in subsequent test cases/scenarios implementation and maintenance. For an example of similar efforts take a look at this projects:

- https://github.com/celestiaorg/test-infra - testground
- https://github.com/logos-co/wakurtosis - kurtosis
- https://github.com/guseggert/clustertest-kubo - clustertest
- https://github.com/ethersphere/beekeeper - beekeeper

## Current status

We have done some preliminary assessment of the above tooling and the possible approaches, however, no conclusive answer on which is best for our usecase or even if one is available.

Some preliminary requirements and results have been captured accross several issues, PRs and repositories:

- https://github.com/status-im/nim-codex/issues/345
- https://github.com/status-im/nim-codex/issues/213
- https://github.com/status-im/nim-codex/issues/207
- https://github.com/status-im/nim-codex/issues/191
- https://github.com/status-im/nim-codex/pull/255
- https://github.com/status-im/nim-codex/issues/140
- https://github.com/status-im/nim-codex/issues/173
- https://github.com/status-im/nim-codex/issues/172
- https://github.com/status-im/nim-codex/issues/174
- https://github.com/status-im/nim-codex/issues/281
- https://github.com/status-im/nim-codex/issues/279
- https://github.com/Shorssaud/network-testing-codex

## Next steps

We are currently sourcing two dedicated resources to help us move this effort forward - a [distributed testing engineer](https://jobs.status.im/?gh_jid=4872413), to assist with testing and a [devops engineer](https://jobs.status.im/?gh_jid=4864237), to bootstrap and manage the required infrastructure - come work with us if you like the challenge ;-).

As it currently stands, we need to understand the following:

1. [ ] What are our infrastructure requirements for the testnets and the distributed tests?
2. [ ] Understand and document testing framework and approach suits us best?
   1. [ ] What features are supported out of the box, which are planed and the expected timeline?
   2. [ ] Assess the need of an in house solution or major external contribution to an existing project?
3. [ ] Define and document initial testing scenarios and their respective requirements - see (1)
